### ISSUE TITLE
Best practices for managing environment variables?

### ISSUE THREAD

**Issue by zckly** [chocolat-chaud-io/stator#123]
Hey @yann510 ! 

Thank you so much for this amazing template. It's helped me learn so much about best practices for building a full stack app <3

Just had a quick question that I've been hitting my head on. What's your go-to for managing env variables in Stator? I tried cloning, running `npm run gen-started` and deploying via Digital Ocean but hit an error about the database env variables not being defined (like `database.HOSTNAME`).

Sorry if this is kind of a noob question 😅

**Comment by yann510** [comment]
Hey @zckly,

Thank you for the kind words!

I will try myself to deploy the application on DigitalOcean and let you know what's up.
Maybe we pushed something that broke this flow.

**Comment by yann510** [comment]
@zckly there was indeed a bug, which will get fixed when #124 merges :)

Thanks for pointing this out!
