### ISSUE TITLE
Ask to be part of NestJS awesome list

### ISSUE THREAD

**Issue by yann510** [chocolat-chaud-io/stator#41]
https://github.com/juliandavidmr/awesome-nestjs#components--libraries

**Comment by GabrielBottari** [comment]
And add appropriate badge to readme 
![image](https://user-images.githubusercontent.com/28274198/96392823-3b6c1f00-118b-11eb-96f2-2c28a5520e49.png)

**Comment by yann510** [comment]
Waiting for this PR to be processed: https://github.com/juliandavidmr/awesome-nestjs/pull/124

**Comment by yann510** [comment]
Need to add the badge in order to close this one.
